sudo: required
services:
    - docker
script:
    - docker build -t mnsbutterfly/risc .
    - docker images mnsbutterfly/risc

before_deploy:
    - docker login --username mnsbutterfly --password inthemiddle#11

deploy:
    provider: script
    script: docker push mnsbutterfly/risc
    on:
        branch: master