version: 0.2

phases:
    install:
        commands:
            - echo Executing Install Phase
        finally:
            - echo Executing Install Finally
    pre_build:
        commands:
            - npm install
        finally:
            - echo Executing Pre Build Finally    
    build:
        commands:
            - npm build 
        finally:
            - echo Executing Build Finally
    post_build:
        commands:
            - echo Executing Post Build Phase
        finally:
            - echo Executing Post Build Finally
    